# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do


    desc "Runs all the tests"
    lane :test do
        scan
    end


    desc "Build app for beta distribution"
    lane :build do

        sh("security unlock-keychain -p niit@123 /Users/Shared/Jenkins/Documents/jenkins.keychain", log: false)
        setup_jenkins
        gym(
            scheme: "JenkinsFastlanePipeTest",
            export_method: "app-store",
            export_options: {
                provisioningProfiles: {
                    "com.dbsystel.JenkinsFastlanePipeTest" => "JenkinsFastlanePipeTestPratibha.mobileprovision",
                }
            }
        )
        upload_to_testflight
    end


    desc "Push a new beta build to TestFlight"
    lane :beta do
#upload_to_testflight
        #pilot(
            #changelog: "release notes",
            #skip_submission:true,
            #distribute_external:true,
            #skip_waiting_for_build_processing:true
        #)
    end

# You can define as many lanes as you want

    after_all do |lane|
    # This block is called, only if the executed lane was successful
        if ENV["SLACK_URL"]
            slack(
                #slack_url: "https://hooks.slack.com/services/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",
                channel: "jenkinspipelineapp",
                message: "Successfully deployed new App Update."
            )
        end
    end

    error do |lane, exception|
        if ENV["SLACK_URL"]
            slack(
                #slack_url: "https://hooks.slack.com/services/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",
                message: exception.message,
                success: false
            )
        end
    end

end
