# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Push a new beta build to TestFlight"
  lane :beta do
    setup_jenkins
    unlock_keychain( # Unlock an existing keychain and add it to the keychain search list
        path: "/Users/pratibha/Library/Keychains/login.keychain-db",
        password: "niit@123",
        set_default: true
    )
    build_app(
        scheme: "JenkinsFastlanePipeTest",
        export_method: "app-store",
        export_options: {
            provisioningProfiles: {
                "com.dbsystel.JenkinsFastlanePipeTest" => "JenkinsFastlanePipeTestPratibha.mobileprovision",
            }
        },
    upload_to_testflight
  end
end
